### ISSUE TITLE
Segfault on startup due to background

### ISSUE THREAD

**Issue by Timidger** [Immington-Industries/way-cooler#117] opened 2016-10-08 19:06 UTC
The background image is loaded up, and then mysteriously destroyed just a moment later. This causes a segfault, and Way Cooler terminates. Tested as of 034dcbe (current master), on Arch Linux 64bit.

WORKAROUND: Set the color in the configuration file to be empty, and it should work as the background will then not load.

**Comment by SnirkImmington** [comment] 2016-10-11 13:55
Duplicate of #115 || fixed in 21bd2c4 ?

**Comment by Timidger** [comment] 2016-10-11 15:36
Not dup, but was mentioned. This is a separate issue.

**Closed** 2016-10-11 15:36 UTC
Labels: bug, tiling
